name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # Ou a branch principal que você usa

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # A branch para a qual será feito o deploy
          folder: dist # A pasta que será implantada (resultado do 'npm run build')
